// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { SignalCoverage, signalColour } from './signalCoverage';
import type { Map as MapLibreMap } from 'maplibre-gl';
it('loads measurements, colours markers, shows details and clears them on close', async () => {
  const setData = vi.fn();
  const map = { on:vi.fn(), off:vi.fn(), isStyleLoaded:()=>true, getSource:()=>({setData}) };
  const receiver = {id:'n-rx',label:'Receiver',role:'repeater',lat:44,lng:-77};
  vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({excluded:{},summaries:[{transmitter:receiver,receiver,samples:2,firstAt:1,lastAt:2,locationQuality:'stale',rssi:{count:2,median:-100,min:-110,max:-90}}]})}));
  const parent = document.createElement('div'); document.body.append(parent);
  const overlay = new SignalCoverage(map as unknown as MapLibreMap,parent);
  overlay.show({...receiver,role:'repeater',observer:true,lastSeen:2});
  await vi.waitFor(()=>expect(parent.textContent).toContain('1 measurement groups'));
  const inputs = parent.querySelectorAll<HTMLInputElement>('.signal-prediction-form input');
  expect(inputs).toHaveLength(6);
  inputs.forEach((input) => { input.value = '1'; });
  parent.querySelector<HTMLFormElement>('.signal-prediction-form')!.requestSubmit();
  expect(parent.textContent).toContain('Saved locally');
  const data = setData.mock.calls.at(-1)?.[0];
  expect(data.features[0].properties).toMatchObject({colour:'#70c5ed',sparse:true,uncertain:true});
  const list = parent.querySelector<HTMLSelectElement>('[aria-label="Inspect measurement location"]')!;
  list.value='0'; list.dispatchEvent(new Event('change'));
  expect(parent.textContent).toContain('range -110 to -90 dBm');
  expect(parent.textContent).not.toContain('SNR:');
  overlay.close(); expect(setData.mock.calls.at(-1)?.[0].features).toEqual([]);
  expect(parent.classList.contains('coverage-open')).toBe(false);
  overlay.destroy(); parent.remove();
  expect(signalColour(-120,'rssi')).toBe('#e9b66e');
  expect(signalColour(10,'snr')).toBe('#59dfba');
});
afterEach(()=>{vi.unstubAllGlobals(); vi.restoreAllMocks();});
